---
# file: roles/mysql-rpm-repo/tasks/main.yml

- name: ensure MySQL Yum repo is installed
  when: ansible_os_family == "RedHat"
  shell: rpm -Uvh http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm
           creates=/etc/yum.repos.d/mysql-community.repo

- name: install libselinux-python from yum
  when: ansible_os_family == "RedHat"
  yum: name=libselinux-python state=present
