---
- name: install unzip from yum
  when: ansible_os_family == "RedHat"
  yum: name=unzip state=present

- name: install unzip from apt
  when: ansible_os_family == "Debian" and inventory_hostname != "privatlakarportal-demo" 
  apt: name=unzip state=present
