apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: logsender
  name: logsender
spec:
  output:
    to:
      kind: ImageStreamTag
      name: logsender:latest
  resources: {}
  source:
    git:
      ref: develop
      uri: https://github.com/sklintyg/logsender.git
    contextDir: /
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: commonVersion
        value: 3.6.0.+
      - name: infraVersion
        value: 3.6.0.+
      - name: buildVersion
        value: 3.6.0.0-OPENSHIFT
      - name: ARTIFACT_DIR
        value: build/libs
      from:
        kind: "ImageStreamTag"
        name: "intyg-s2i:latest"
      forcePull: true

